Repository Help-M-Ssaem/front-end, pull requests merged in 2023-08, with the labels that each got.

#73 [Feat] 댓글 작성 api 연동 완료
  src/assets/CommentIcons.tsx
  src/components/board/Board.tsx
  src/components/board/comment/Comment.tsx
  src/components/button/Button.tsx
  src/components/chatting/CurrentChattingForm.tsx
  src/components/comment/Comment.tsx
  src/components/input/Input.tsx
  src/constants/boardKey.ts
  src/constants/commentKey.ts
  src/hooks/board/comment/useBoardBestComment.tsx
  src/hooks/board/comment/useBoardComment.tsx
  src/hooks/board/comment/useBoardCommentCreate.tsx
  src/hooks/board/comment/useBoardCommentDelete.tsx
  src/hooks/board/comment/useBoardCommentLike.tsx
  src/interfaces/board.ts
  src/interfaces/comment.ts
  src/pages/auth/UserInfo.tsx
  src/pages/board/detail.tsx
  src/pages/matching/detail.tsx
  src/pages/mypage/mypage.tsx
Labels: feat

#69 [Feat] 고민글 서버연결2
  src/App.tsx
  src/components/matching/Matching.tsx
  src/components/matching/Mssaem.tsx
  src/components/matching/mapingMatching/MbtiList.tsx
  src/components/matching/mapingMatching/WorryList.tsx
  src/constants/debateKey.ts
  src/constants/matchingKey.ts
  src/hooks/worry/UseFetchBoardList.tsx
  src/hooks/worry/useCreateWorry.tsx
  src/hooks/worry/useDeleteWorry.tsx
  src/hooks/worry/useDetailPost.tsx
  src/hooks/worry/useUpdatedWorry.tsx
  src/interfaces/matching.ts
  src/interfaces/worry.ts
  src/pages/matching/create.tsx
  src/pages/matching/detail.tsx
  src/pages/matching/matching.tsx
  src/pages/matching/update.tsx
Labels: feat

#79 [Design] 고민글 인터페이스 및 디자인 수정
  src/components/matching/Matching.tsx
  src/components/matching/mapingMatching/WorryList.tsx
  src/hooks/main/useMainTeacher.tsx
  src/interfaces/worry.ts
Labels: desgin, docs

#82 [Feat] 토론글 서버 연결
  src/App.tsx
  src/components/button/plusbutton/PlusButton.tsx
  src/components/button/plusbutton/RedButton.tsx
  src/components/debate/debate.tsx
  src/components/debate/vote/VoteItem.tsx
  src/components/debate/vote/VoteItemList.tsx
  src/constants/debateKey.ts
  src/hooks/debate/comment/useDebateBestComment.tsx
  src/hooks/debate/comment/useDebateComment.tsx
  src/hooks/debate/comment/useDebateCommentCreate.tsx
  src/hooks/debate/comment/useDebateCommentDelete.tsx
  src/hooks/debate/comment/useDebateCommentLike.tsx
  src/hooks/debate/useCreateDebate.tsx
  src/hooks/debate/useDebateList.tsx
  src/hooks/debate/useDeleteDebate.tsx
  src/hooks/debate/useDetailDebate.tsx
  src/hooks/debate/useUpdateDebate.tsx
  src/interfaces/debate.ts
  src/pages/debate/create.tsx
  src/pages/debate/detail.tsx
  src/pages/debate/postlist.tsx
  src/pages/debate/update.tsx
  src/states/debateState.ts
Labels: feat, docs

#83 [Refactor] 댓글 관련 리팩토링
  src/assets/CommentIcons.tsx
  src/components/auth/Login.tsx
  src/components/auth/NotLogin.tsx
  src/components/board/comment/Comment.tsx
  src/components/board/comment/CommentCreate.tsx
  src/components/button/Button.tsx
  src/components/chatting/CurrentChatting.tsx
  src/components/chatting/CurrentChattingForm.tsx
  src/components/container/Container.tsx
  src/components/header/Header.tsx
  src/components/main/Hot.tsx
  src/components/modal/EvaluationModal.tsx
  src/components/modal/ExitModal.tsx
  src/components/modal/ReportModal.tsx
  src/hooks/board/comment/useBoardBestComment.tsx
  src/pages/board/create.tsx
  src/pages/board/detail.tsx
  src/pages/board/mbti.tsx
  src/pages/board/update.tsx
  src/pages/chatting/chatting.tsx
  src/pages/debate/create.tsx
  src/pages/main/main.tsx
  src/pages/matching/create.tsx
  src/pages/matching/detail.tsx
  src/pages/matching/update.tsx
  src/pages/search/search.tsx
Labels: refactor

#85 [Feat] 고민글 페이지, 특정 멤버조회
  src/components/matching/mapingMatching/WorryList.tsx
  src/hooks/worry/UseFetchBoardList.tsx
  src/hooks/worry/useWorryPostListMember.tsx
  src/hooks/worry/useWorrySolveListMember.tsx
  src/interfaces/worry.ts
  src/pages/debate/create.tsx
  src/pages/debate/detail.tsx
  src/pages/mypage/mypage.tsx
Labels: desgin, docs, fix

#87 [Feat] Hot토론글, 토론글 페이지네이션
  src/components/debate/pageMapingDebate/PageDebate.tsx
  src/components/debate/vote/VoteItem.tsx
  src/components/main/HotDebate.tsx
  src/hooks/debate/useDebatePaging.tsx
  src/pages/debate/detail.tsx
  src/pages/debate/postlist.tsx
  src/pages/main/hotDebate.tsx
  src/pages/main/main.tsx
Labels: desgin, feat, docs

#91 [Fix] conflict 중간 점검
  src/components/debate/vote/VoteItem.tsx
  src/components/debate/vote/VoteItemList.tsx
  src/components/matching/Matching.tsx
  src/components/matching/mapingMatching/MbtiList.tsx
  src/components/matching/mapingMatching/WorryList.tsx
  src/hooks/debate/comment/useDebateCommentCreate.tsx
  src/hooks/debate/comment/useDebateCommentDelete.tsx
  src/hooks/debate/useCreateDebate.tsx
  src/hooks/debate/useDeleteDebate.tsx
  src/hooks/debate/useDetailDebate.tsx
  src/hooks/worry/UseFetchBoardList.tsx
  src/hooks/worry/useCreateWorry.tsx
  src/hooks/worry/useDetailPost.tsx
  src/hooks/worry/useWorryPostListMember.tsx
  src/hooks/worry/useWorrySolveListMember.tsx
  src/interfaces/debate.ts
  src/interfaces/worry.ts
Labels: fix

#92 [Fix] conflict 추가 수정
  src/pages/mypage/mypage.tsx
Labels: fix

#99 [Fix] 대댓글 기능 추가
  src/components/board/comment/Comment.tsx
  src/hooks/board/comment/useBoardCommentCreate.tsx
  src/pages/board/detail.tsx
  src/pages/board/mbti.tsx
Labels: feat, fix

#101 [Fix]충돌 해결
  package-lock.json
  package.json
  src/App.tsx
  src/apis/axios.ts
  src/components/Pagination/ListPagination.tsx
  src/components/Pagination/SelectBox.tsx
  src/components/auth/CommunityPolicy.tsx
  src/components/auth/CommunityPolicyText.tsx
  src/components/auth/PrivacyPolicy.tsx
  src/components/auth/PrivacyPolicyText.tsx
  src/components/chatting/CurrentChatting.tsx
  src/components/footer/Footer.tsx
  src/components/modal/EvaluationModal.tsx
  src/hooks/mypage/useEvaluation.tsx
  src/hooks/user/useGetToken.tsx
  src/hooks/worry/useEvaluation.tsx
  src/interfaces/chatting.ts
  src/pages/auth/login.tsx
  src/pages/auth/signin.tsx
  src/pages/chatting/chatting.tsx
  src/pages/mypage/mypage.tsx
  src/styles/GlobalStyle.tsx
Labels: bug

#104 [Fix] 메인페이지 관련 오류 수정
  src/components/board/Board.tsx
  src/components/main/HotBoard.tsx
  src/components/main/HotDebate.tsx
Labels: fix

#105 [Fix] MBTI별 게시판 관련 오류
  src/components/matching/mapingMatching/WorryList.tsx
  src/components/text/Text.tsx
  src/hooks/board/useBoardList.tsx
  src/interfaces/board.ts
  src/pages/board/board.tsx
  src/pages/board/create.tsx
  src/pages/board/detail.tsx
  src/pages/board/mbti.tsx
  src/pages/main/hotBoard.tsx
  src/pages/main/hotDebate.tsx
  src/pages/main/main.tsx
  src/pages/matching/matching.tsx
Labels: fix

#108 [Feat] 현재 로그인한 회원 정보 조회
  src/components/auth/Login.tsx
  src/components/header/Header.tsx
  src/constants/userKey.ts
  src/hooks/board/useBoardListMember.tsx
  src/hooks/user/useMemberInfo.tsx
  src/hooks/user/useProfile.tsx
  src/interfaces/user.ts
  src/pages/main/main.tsx
  src/pages/mypage/mypage.tsx
  src/pages/mypage/update.tsx
Labels: desgin, feat

#116 [Fix] 토큰 갱신, 디자인 수정
  src/App.tsx
  src/apis/axios.ts
  src/assets/CommonIcons.tsx
  src/assets/logo/Naver.svg
  src/components/Pagination/SelectBox.tsx
  src/components/checkbox/SelectAllcheckbox.tsx
  src/components/input/Input2.tsx
  src/components/modal/EvaluationModal.tsx
  src/components/mypage/mbtiBox.tsx
  src/components/mypage/nameBox.tsx
  src/hooks/user/signup.tsx
  src/hooks/user/useGetToken.tsx
  src/pages/auth/UserInfo.tsx
  src/pages/auth/login.tsx
  src/pages/board/mbti.tsx
  src/pages/main/main.tsx
  src/pages/mypage/update.tsx
Labels: desgin, fix

#115 [Fix] 전체 디자인 수정 및 마이페이지 경로 수정
  src/App.tsx
  src/components/auth/Login.tsx
  src/components/board/Board.tsx
  src/components/debate/debate.tsx
  src/components/main/HotDebate.tsx
  src/components/matching/Matching.tsx
  src/components/matching/Mssaem.tsx
  src/components/matching/mapingMatching/WorryList.tsx
  src/components/profile/MatchingProfile.tsx
  src/pages/board/mbti.tsx
  src/pages/debate/detail.tsx
  src/pages/main/main.tsx
  src/pages/matching/detail.tsx
  src/pages/usePage/ProfilePage.tsx
  src/pages/usePage/UserPage.tsx
  src/pages/usePage/mypage.tsx
  src/pages/usePage/update.tsx
Labels: desgin, feat, docs, fix

#118 [Fix] 게시판 관련 오류 수정
  src/assets/CommonIcons.tsx
  src/components/header/Header.tsx
  src/components/main/Hot.tsx
  src/components/mbti/Mbti.tsx
  src/constants/boardKey.ts
  src/hooks/board/category/useCategoryCount.tsx
  src/pages/board/detail.tsx
  src/pages/board/mbti.tsx
  src/pages/board/update.tsx
  src/pages/main/main.tsx
Labels: feat, fix

#120 [Design] 검색 결과페이지 디자인, api연결(1)
  src/App.tsx
  src/components/debate/debate.tsx
  src/components/search/SearchBar.tsx
  src/hooks/board/useBoardList.tsx
  src/hooks/search/search.tsx
  src/interfaces/board.ts
  src/pages/search/moreBoardResult.tsx
  src/pages/search/moreDebateResult.tsx
  src/pages/search/moreMatchingResult.tsx
  src/pages/search/result.tsx
  src/pages/search/search.tsx
Labels: desgin, feat

#122 Fix: search hooks 관련 이슈 수정 (#121)
  src/hooks/search/search.tsx
  src/pages/search/result.tsx
Labels: fix

#123 [Feat] 채팅 기능 구현
  package-lock.json
  package.json
  src/assets/ChattingIcons.tsx
  src/assets/CommonIcons.tsx
  src/assets/logo/Google.svg
  src/components/auth/Login.tsx
  src/components/board/Board.tsx
  src/components/chatting/ChattingComponent.tsx
  src/components/chatting/ChattingForm.tsx
  src/components/chatting/CurrentChatting.tsx
  src/components/chatting/CurrentChattingForm.tsx
  src/components/chatting/MessageItem.tsx
  src/components/hamburger/Hamburger.tsx
  src/constants/chattingKey.ts
  src/hooks/chatting/useChatMessages.tsx
  src/hooks/chatting/useChatRooms.tsx
  src/interfaces/chatting.ts
  src/pages/chatting/chatting.tsx
  src/pages/debate/create.tsx
  src/pages/matching/detail.tsx
  src/states/chatting.ts
  src/utils/.gitkeep
  src/utils/Time.tsx
Labels: feat

#137 [Fix] 댓글 관련 오류
  src/components/board/comment/CommentCreate.tsx
Labels: fix

#138 [Fix] 게시판 관련 오류
  src/apis/axios.ts
  src/components/text/Text.tsx
  src/interfaces/board.ts
  src/pages/board/create.tsx
  src/pages/board/detail.tsx
  src/pages/board/mbti.tsx
  src/pages/board/update.tsx
Labels: feat, fix

#141 [Fix] 프로필 관련 오류
  src/apis/axios.ts
  src/components/auth/Login.tsx
  src/components/board/Board.tsx
  src/components/board/comment/Comment.tsx
  src/components/debate/debate.tsx
  src/components/debate/myDebate.tsx
  src/components/header/Header.tsx
  src/components/main/HotBoard.tsx
  src/components/main/HotDebate.tsx
  src/components/profile/Profile.tsx
  src/pages/board/detail.tsx
  src/pages/chatting/chatting.tsx
  src/pages/debate/detail.tsx
Labels: fix

#151 Fix/#144
  src/assets/CommonIcons.tsx
  src/assets/side/RedButtonIcons.tsx
  src/components/alarm/Alarm.tsx
  src/components/alarm/Favorites.tsx
  src/components/debate/comment/Comment.tsx
  src/components/debate/comment/CommentCreate.tsx
  src/components/debate/debate.tsx
  src/components/debate/pageMapingDebate/PageDebate.tsx
  src/components/hamburger/Hamburger.tsx
  src/components/header/Header.tsx
  src/components/matching/mapingMatching/WorryList.tsx
  src/components/search/SearchBar.tsx
  src/components/side/Alarm.tsx
  src/components/side/Favorites.tsx
  src/constants/alarmKey.ts
  src/hooks/alarm/useDeletAlarm.tsx
  src/hooks/alarm/usePageAlarm.tsx
  src/hooks/alarm/useReadAlarm.tsx
  src/hooks/debate/comment/useDebateCommentDelete.tsx
  src/hooks/debate/comment/useDebateCommentLike.tsx
  src/hooks/debate/useDebatePaging.tsx
  src/hooks/keywords/useGetPopularSearch.tsx
  src/hooks/keywords/useGetRecentSearch.tsx
  src/hooks/keywords/usePostSearchWord.tsx
  src/hooks/worry/UseFetchBoardList.tsx
  src/interfaces/alarm.tsx
  src/interfaces/keyword.ts
  src/interfaces/worry.ts
  src/pages/alarm/alarm.tsx
  src/pages/debate/detail.tsx
  src/pages/debate/postlist.tsx
  src/pages/main/hotDebate.tsx
  src/pages/matching/create.tsx
  src/pages/matching/detail.tsx
  src/pages/matching/matching.tsx
  src/pages/search/search.tsx
  src/states/debate.ts
Labels: feat, fix

#154 [Fix] MBTI별 게시판 최종 사진 업로드 추가
  src/pages/board/create.tsx
  src/pages/board/update.tsx
Labels: fix

#158 [Fix] 토론 페이지네이션 훅 수정, 투표시 바로 반영
  src/components/debate/pageMapingDebate/PageDebate.tsx
  src/components/debate/vote/VoteItem.tsx
  src/components/main/HotWorry.tsx
  src/components/matching/Matching.tsx
  src/hooks/alarm/usePageAlarm.tsx
  src/hooks/debate/useDebatePaging.tsx
  src/hooks/debate/useVoteItem.tsx
  src/pages/alarm/alarm.tsx
  src/pages/main/main.tsx
  src/pages/matching/detail.tsx
  src/pages/matching/matching.tsx
Labels: fix

#161 [Fix] 유저수정페이지 이미지 삭제, 최대 글자수 설정
  src/components/Pagination/ListPagination.tsx
  src/components/chatting/CurrentChatting.tsx
  src/components/input/Input2.tsx
  src/components/modal/EvaluationModal.tsx
  src/components/mypage/nameBox.tsx
  src/hooks/chatting/useChatRooms.tsx
  src/interfaces/chatting.ts
  src/pages/auth/UserInfo.tsx
  src/pages/usePage/update.tsx
Labels: fix

#164 [Fix] 해결완료 수정
  src/components/chatting/CurrentChatting.tsx
Labels: fix

#165 [Feat] 검색 더보기페이지 api 연결
  src/components/search/SearchBar.tsx
  src/hooks/board/useBoardList.tsx
  src/hooks/search/useSearchBoardList.tsx
  src/hooks/search/useSearchDebateList.tsx
  src/hooks/search/useSearchSolvedWorryBoardList.tsx
  src/hooks/search/useSearchWaitingWorryBoardList.tsx
  src/interfaces/moresearch.ts
  src/pages/search/moreBoardResult.tsx
  src/pages/search/moreDebateResult.tsx
  src/pages/search/moreMatchingResult.tsx
  src/pages/search/result.tsx
Labels: feat

#169 [Fix] 유저 수정페이지 오류 수정
  src/components/mypage/MyPage.tsx
  src/pages/usePage/UserPage.tsx
  src/pages/usePage/mypage.tsx
  src/pages/usePage/update.tsx
Labels: fix

#172 [Fix] 고민/토론 일부 수정
  src/components/debate/debate.tsx
  src/components/debate/vote/VoteItem.tsx
  src/components/matching/mapingMatching/WorryList.tsx
  src/components/modal/ReportModal.tsx
  src/components/modal/ShareModal.tsx
  src/hooks/report/useReportPost.tsx
  src/interfaces/worry.ts
  src/pages/matching/detail.tsx
Labels: fix

#177 [Fix] 유저 수정 페이지, 로그아웃 수정
  src/App.tsx
  src/components/auth/Login.tsx
  src/hooks/user/useMemberInfo.tsx
  src/pages/usePage/update.tsx
Labels: fix

#179 [Fix] 로그아웃 수정
  src/components/auth/Login.tsx
  src/pages/usePage/update.tsx
Labels: fix

#173 [Fix] 마이페이지 활동내역 api 연결 수정
  src/App.tsx
  src/components/Pagination/SelectBox.tsx
  src/components/mypage/ActivityList.tsx
  src/components/mypage/MyActivityList.tsx
  src/components/search/SearchBar.tsx
  src/hooks/keywords/usePostSearchWord.tsx
  src/pages/search/moreMatchingResult.tsx
  src/pages/search/result.tsx
  src/pages/search/search.tsx
  src/pages/userPage/ProfilePage.tsx
  src/pages/userPage/UserPage.tsx
  src/pages/userPage/mypage.tsx
  src/pages/userPage/update.tsx
Labels: fix

#182 [Fix] 토론 댓글 삭제, 좋아요
  src/components/alarm/Alarm.tsx
  src/components/button/plusbutton/RedButton.tsx
  src/components/debate/comment/Comment.tsx
  src/components/debate/comment/CommentCreate.tsx
  src/components/debate/debate.tsx
  src/components/debate/pageMapingDebate/PageDebate.tsx
  src/components/debate/vote/VoteItem.tsx
  src/components/debate/vote/VoteItemList.tsx
  src/components/search/SearchBar.tsx
  src/hooks/board/useBoardDetail.tsx
  src/hooks/debate/useDetailDebate.tsx
  src/hooks/keywords/useGetRecentSearch.tsx
  src/hooks/keywords/usePostSearchWord.tsx
  src/interfaces/debate.ts
  src/pages/debate/detail.tsx
  src/states/debate.ts
Labels: fix

#183 [Fix] 유저 수정 페이지 뱃지 , 비율 수정
  src/components/badge/Badge.tsx
  src/components/mypage/MyActivityList.tsx
  src/pages/userPage/UserPage.tsx
  src/pages/userPage/mypage.tsx
  src/pages/userPage/update.tsx
Labels: fix

#187 [Fix] 고민글 리로딩 제거
  src/components/matching/mapingMatching/WorryList.tsx
  src/pages/main/main.tsx
  src/pages/search/search.tsx
Labels: fix

#188 [Fix] 유저수정페이지
  src/components/badge/Badge.tsx
  src/pages/userPage/mypage.tsx
  src/pages/userPage/update.tsx
Labels: fix

#189 [Fix] 유저페이지비율수정
  src/components/mypage/ActivityList.tsx
  src/pages/userPage/UserPage.tsx
  src/pages/userPage/mypage.tsx
  src/pages/userPage/update.tsx
Labels: fix

#192 [Fix] 토론 고민글 생성 시 최소 제한
  src/components/debate/pageMapingDebate/PageDebate.tsx
  src/pages/debate/create.tsx
  src/pages/matching/create.tsx
Labels: bug, fix

#193 [Fix] 하단 검색바 검색 페이지 이동
  src/App.tsx
  src/components/Pagination/SelectBox.tsx
  src/components/debate/pageMapingDebate/PageDebate.tsx
  src/components/matching/mapingMatching/WorryList.tsx
  src/components/search/SearchBar.tsx
  src/pages/board/mbti.tsx
  src/pages/board/search.tsx
  src/pages/main/hotBoard.tsx
  src/pages/search/moreBoardResult.tsx
  src/pages/search/moreDebateResult.tsx
  src/pages/search/moreMatchingResult.tsx
  src/pages/search/result.tsx
  src/pages/search/search.tsx
Labels: fix

#199 [Fix] 회원가입, 아이디 찾기 제거
  src/components/auth/NotLogin.tsx
Labels: fix
