Repository Help-M-Ssaem/front-end, pull requests merged in 2023-07, with the labels that each got.

#4 [Docs] 페이지 분리 라우트 작성
  package-lock.json
  package.json
  src/App.tsx
  src/pages/.gitkeep
  src/pages/alarm/alarm.tsx
  src/pages/auth/login.tsx
  src/pages/auth/signin.tsx
  src/pages/board/board.tsx
  src/pages/board/create.tsx
  src/pages/board/free.tsx
  src/pages/board/mbti.tsx
  src/pages/board/update.tsx
  src/pages/chatting/chatting.tsx
  src/pages/debate/create.tsx
  src/pages/debate/debate.tsx
  src/pages/debate/update.tsx
  src/pages/favorites/favorites.tsx
  src/pages/main/main.tsx
  src/pages/matching/matching.tsx
  src/pages/mbtitype/mbtitype.tsx
  src/pages/user/user.tsx
Labels: feat, docs

#7 [Feat] Header 컴포넌트 생성
  src/App.tsx
  src/components/header/Header.tsx
  src/components/layout/layout.tsx
  src/constants/.gitkeep
  src/constants/CommonIcons.tsx
  src/constants/HeaderIcons.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Introduction.mdx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/code-brackets.svg
  src/stories/assets/colors.svg
  src/stories/assets/comments.svg
  src/stories/assets/direction.svg
  src/stories/assets/flow.svg
  src/stories/assets/plugin.svg
  src/stories/assets/repo.svg
  src/stories/assets/stackalt.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  src/styles/color.ts
Labels: desgin, feat

#10 [Fix] header 컴포넌트 navbar 라우팅 오류 수정
  package-lock.json
  package.json
  src/components/header/Header.tsx
  src/components/layout/layout.tsx
  src/states/navbar.ts
Labels: fix

#13 [Design] pretendard 전역 글꼴 설정
  package-lock.json
  package.json
  public/index.html
  src/components/header/Header.tsx
  src/styles/GlobalStyle.tsx
  src/styles/font.ts
Labels: desgin

#14 [Design] 게시판 조회 페이지
  package-lock.json
  package.json
  src/App.tsx
  src/assets/CommonIcons.tsx
  src/assets/HeaderIcons.tsx
  src/components/badge/badge.tsx
  src/components/board/board.tsx
  src/components/button/button.tsx
  src/components/container/container.tsx
  src/components/header/Header.tsx
  src/components/layout/layout.tsx
  src/components/mbti/Mbti.tsx
  src/constants/CommonIcons.tsx
  src/interfaces/.gitkeep
  src/interfaces/board.ts
  src/pages/board/board.tsx
  src/pages/board/free.tsx
  src/pages/board/mbti.tsx
  src/states/.gitkeep
  src/states/navbar.ts
  src/styles/animation.ts
  src/styles/font.ts
Labels: desgin

#15 [Design] mbti 게시판 조회 페이지 완료
  src/App.tsx
  src/assets/CommonIcons.tsx
  src/components/mbti/Mbti.tsx
  src/pages/board/board.tsx
  src/pages/board/free.tsx
  src/pages/board/mbti.tsx
  src/states/board.ts
  src/states/navbar.ts
  src/styles/GlobalStyle.tsx
Labels: desgin, fix

#16 [Feat] 게시판 생성 페이지 완료 editor
  package-lock.json
  package.json
  src/App.tsx
  src/assets/HeaderIcons.tsx
  src/components/button/Button.tsx
  src/components/container/Container.tsx
  src/components/header/Header.tsx
  src/components/layout/Layout.tsx
  src/components/scroll/ScrollToTop.tsx
  src/pages/board/create.tsx
  src/pages/board/mbti.tsx
  src/styles/color.ts
  src/styles/font.ts
Labels: desgin, feat

#18 [Feat#17] 로그인, 푸터, 이용약관 페이지 구현
  package-lock.json
  package.json
  src/App.tsx
  src/assets/CommonIcons.tsx
  src/assets/HeaderIcons.tsx
  src/assets/logo/CatLogo.svg
  src/assets/logo/Google.svg
  src/assets/logo/Kakao.svg
  src/assets/logo/Naver.svg
  src/components/checkbox/SelectAllcheckbox.tsx
  src/components/checkbox/checkbox.tsx
  src/components/footer/Footer.tsx
  src/pages/auth/GoogleLogin.tsx
  src/pages/auth/KakaoLogin.tsx
  src/pages/auth/login.tsx
  src/pages/auth/signin.tsx
Labels: desgin, feat

#26 [Fix] Header 라우트 오류 수정
  src/assets/ButtonIcons.tsx
  src/assets/CommonIcons.tsx
  src/components/board/Board.tsx
  src/components/board/BoardDetail.tsx
  src/components/comment/Comment.tsx
  src/components/footer/Footer.tsx
  src/components/header/Header.tsx
  src/components/input/Input.tsx
  src/components/profile/Profile.tsx
  src/interfaces/comment.ts
  src/pages/board/create.tsx
  src/pages/board/mbti.tsx
  src/pages/board/update.tsx
Labels: fix

#27 [Design] Matching 페이지 디자인
  src/App.tsx
  src/assets/CommonIcons.tsx
  src/components/badge/Badge.tsx
  src/components/header/Header.tsx
  src/components/matching/Matching.tsx
  src/interfaces/matching.ts
  src/pages/board/mbti.tsx
  src/pages/matching/create.tsx
  src/pages/matching/match.tsx
  src/pages/matching/matching.tsx
  src/pages/matching/update.tsx
Labels: desgin

#34 [Design] Main 페이지 디자인, 서버 연결 설정
  .gitignore
  package-lock.json
  package.json
  src/App.tsx
  src/apis/.gitkeep
  src/apis/axios.ts
  src/components/auth/Login.tsx
  src/components/auth/NotLogin.tsx
  src/components/badge/Badge.tsx
  src/components/container/Container.tsx
  src/components/main/Hot.tsx
  src/components/profile/Profile.tsx
  src/components/text/Text.tsx
  src/constants/boardKey.ts
  src/hooks/.gitkeep
  src/hooks/main/useHotBoard.tsx
  src/interfaces/board.ts
  src/interfaces/user.ts
  src/pages/board/mbti.tsx
  src/pages/main/main.tsx
  src/pages/user/user.tsx
Labels: desgin

#30 [Design] 유저 정보 페이지
  package-lock.json
  package.json
  src/App.tsx
  src/assets/CommonIcons.tsx
  src/custom.d.ts
  src/pages/auth/GoogleLogin.tsx
  src/pages/auth/UserInfo.tsx
  src/pages/auth/login.tsx
  src/pages/auth/signin.tsx
  tsconfig.json
Labels: desgin

#36 [Feat] main 페이지 서버 연동 (HOT 게시글, HOT 토론)
  src/assets/MainIcons.tsx
  src/components/auth/Login.tsx
  src/components/main/Hot.tsx
  src/constants/boardKey.ts
  src/hooks/main/useHotBoard.tsx
  src/hooks/main/useHotDebate.tsx
  src/interfaces/board.ts
  src/interfaces/debate.ts
  src/interfaces/user.ts
  src/pages/main/main.tsx
Labels: feat

#20 [Design] 토론 게시판 조회 페이지, 생성페이지 구현
  src/App.tsx
  src/assets/CommonIcons.tsx
  src/components/button/Button.tsx
  src/components/debate/debate.tsx
  src/components/debate/plusbutton/PlusButton.tsx
  src/components/header/Header.tsx
  src/components/matching/Matching.tsx
  src/interfaces/debate.ts
  src/interfaces/matching.ts
  src/pages/board/mbti.tsx
  src/pages/debate/create.tsx
  src/pages/debate/debate.tsx
  src/pages/debate/postlist.tsx
  src/pages/matching/create.tsx
  src/pages/matching/match.tsx
  src/pages/matching/matching.tsx
  src/pages/matching/update.tsx
  src/states/authstate.ts
  src/states/debateState.ts
  src/styles/color.ts
  tsconfig.json
Labels: desgin, feat

#39 [Feat] 서버 연결 테스트용 마스터 계정 추가
  src/App.tsx
  src/apis/axios.ts
  src/components/auth/NotLogin.tsx
  src/components/board/Board.tsx
  src/components/header/Header.tsx
  src/constants/boardKey.ts
  src/hooks/board/useCreateBoard.tsx
  src/interfaces/board.ts
  src/pages/board/create.tsx
  src/pages/board/detail.tsx
  src/pages/board/mbti.tsx
Labels: feat

#45 [Design] 마이페이지
  src/App.tsx
  src/components/mypage/MyPage.tsx
  src/pages/mypage/mypage.tsx
Labels: desgin

#47 [Fix] interface conflict 수정
  src/App.tsx
  src/components/mypage/MyPage.tsx
  src/pages/mypage/mypage.tsx
Labels: fix

#48 [Design] 마이페이지
  src/App.tsx
  src/components/mypage/MyPage.tsx
  src/pages/mypage/mypage.tsx
Labels: desgin

#52 [Design] 검색페이지
  src/App.tsx
  src/components/header/Header.tsx
  src/pages/mypage/mypage.tsx
  src/pages/search/search.tsx
Labels: desgin

#53 [Design] 검색페이지
  src/App.tsx
  src/components/header/Header.tsx
  src/pages/mypage/mypage.tsx
  src/pages/search/search.tsx
Labels: desgin

#58 [Design] 채팅페이지 디자인
  src/components/chatting/ChattingComponent.tsx
  src/components/chatting/CurrentChatting.tsx
  src/components/chatting/CurrentChattingForm.tsx
  src/components/chatting/MessageItem.tsx
  src/components/container/ChatContainer.tsx
  src/components/debate/plusbutton/PlusButton.tsx
  src/components/hamburger/Hamburger.tsx
  src/components/modal/EvaluationModal.tsx
  src/components/modal/ExitModal.tsx
  src/components/modal/ReportModal.tsx
  src/interfaces/chatting.ts
  src/pages/chatting/chatting.tsx
Labels: desgin

#57 [Feat#32] 회원가입 서버 연결
  package-lock.json
  package.json
  public/index.html
  src/App.tsx
  src/apis/axios.ts
  src/assets/logo/Naver.svg
  src/components/auth/Callback.tsx
  src/components/checkbox/checkbox.tsx
  src/hooks/user/signup.tsx
  src/hooks/user/userNickname.tsx
  src/hooks/user/userlogin.tsx
  src/interfaces/signup.ts
  src/pages/auth/GoogleLogin.tsx
  src/pages/auth/KakaoLogin.tsx
  src/pages/auth/UserInfo.tsx
  src/pages/auth/login.tsx
  src/pages/auth/signin.tsx
Labels: enhancement, feat

#64 [Feat] MBTI별 게시판 페이지 api 연동 완료
  src/App.tsx
  src/assets/ButtonIcons.tsx
  src/components/auth/Login.tsx
  src/components/board/Board.tsx
  src/components/main/HotBoard.tsx
  src/components/mbti/Mbti.tsx
  src/constants/boardKey.ts
  src/hooks/board/category/useCategoryBookmark.tsx
  src/hooks/board/category/useCategoryBookmarkUpdate.tsx
  src/hooks/board/useBoardDetail.tsx
  src/hooks/board/useBoardLike.tsx
  src/hooks/board/useBoardList.tsx
  src/hooks/board/useBoardListMbti.tsx
  src/hooks/board/useBoardListMember.tsx
  src/hooks/board/useCreateBoard.tsx
  src/hooks/board/useDeleteBoard.tsx
  src/hooks/board/useUpdateBoard.tsx
  src/interfaces/board.ts
  src/interfaces/debate.ts
  src/interfaces/user.ts
  src/pages/board/create.tsx
  src/pages/board/detail.tsx
  src/pages/board/mbti.tsx
  src/pages/board/update.tsx
Labels: feat

#61 [Feat] 회원가입 연결
  src/App.tsx
  src/components/auth/Callback.tsx
  src/hooks/user/signup.tsx
  src/hooks/user/userlogin.tsx
  src/hooks/worry/useCreateWorry.tsx
  src/hooks/worry/useDeleteWorry.tsx
  src/hooks/worry/useUpdatedWorry.tsx
  src/interfaces/signup.ts
  src/interfaces/userinfo.ts
  src/interfaces/worry.ts
  src/pages/auth/UserInfo.tsx
  src/pages/auth/login.tsx
  src/pages/auth/signin.tsx
  src/pages/matching/create.tsx
  src/pages/matching/detail.tsx
  src/pages/matching/matching.tsx
  src/pages/matching/update.tsx
Labels: desgin, feat
