Repository Help-M-Ssaem/front-end, pull requests merged in 2023-09, with the labels that each got.

#207 [Fix] 로그아웃 에러 , 평가하기 에러
  src/components/auth/Callback.tsx
  src/components/modal/EvaluationModal.tsx
  src/pages/auth/UserInfo.tsx
  src/pages/auth/login.tsx
  src/pages/main/main.tsx
  src/pages/userPage/mypage.tsx
Labels: fix

#212 [Fix] 로그아웃 수정
  src/components/auth/Login.tsx
  src/pages/main/main.tsx
  src/pages/userPage/update.tsx
Labels: fix

#214 [Fix] 로그아웃 수정
  src/pages/auth/login.tsx
Labels: fix

#215 [Fix] 새로고침 수정
  src/pages/main/main.tsx
Labels: fix

#221 [Fix ] 유저 페이지 이미지 비율 조정
  src/pages/userPage/mypage.tsx
Labels: desgin, fix

#223 Feat: 게시판 검색 API 연결
  src/components/Pagination/SelectBox.tsx
  src/components/debate/pageMapingDebate/PageDebate.tsx
  src/components/header/Header.tsx
  src/components/matching/mapingMatching/WorryList.tsx
  src/interfaces/worry.ts
  src/pages/board/mbti.tsx
  src/pages/main/hotBoard.tsx
  src/pages/search/moreBoardResult.tsx
  src/pages/search/moreDebateResult.tsx
  src/pages/search/moreMatchingResult.tsx
  src/pages/search/result.tsx
  src/pages/userPage/mypage.tsx
Labels: feat, fix

#224 Revert "Feat: 게시판 검색 API 연결"
  src/components/Pagination/SelectBox.tsx
  src/components/debate/pageMapingDebate/PageDebate.tsx
  src/components/header/Header.tsx
  src/components/matching/mapingMatching/WorryList.tsx
  src/interfaces/worry.ts
  src/pages/board/mbti.tsx
  src/pages/main/hotBoard.tsx
  src/pages/search/moreBoardResult.tsx
  src/pages/search/moreDebateResult.tsx
  src/pages/search/moreMatchingResult.tsx
  src/pages/search/result.tsx
  src/pages/userPage/mypage.tsx
Labels: fix

#227 [Fix] 토론글 로딩 추가
  src/components/modal/ShareModal.tsx
  src/hooks/debate/useDebatePaging.tsx
  src/hooks/debate/useDetailDebate.tsx
  src/pages/debate/detail.tsx
  src/pages/userPage/mypage.tsx
Labels: fix

#225 Feat: 게시판 검색 API 연결
  src/components/Pagination/SelectBox.tsx
  src/components/debate/pageMapingDebate/PageDebate.tsx
  src/components/matching/mapingMatching/WorryList.tsx
  src/interfaces/worry.ts
  src/pages/board/mbti.tsx
  src/pages/main/hotBoard.tsx
  src/pages/search/moreBoardResult.tsx
  src/pages/search/moreDebateResult.tsx
  src/pages/search/moreMatchingResult.tsx
  src/pages/search/result.tsx
  src/pages/userPage/mypage.tsx
Labels: feat, fix

#230 [Fix] 로그아웃 url 수정, 네이버 버튼 제거
  src/components/auth/Login.tsx
  src/pages/auth/login.tsx
Labels: fix

#237 [Fix] 유저관련페이지 수정, 검색 시 공백제한
  src/apis/axios.ts
  src/components/debate/pageMapingDebate/PageDebate.tsx
  src/components/header/Header.tsx
  src/components/matching/mapingMatching/WorryList.tsx
  src/components/modal/ShareModal.tsx
  src/components/search/SearchBar.tsx
  src/hooks/debate/useDebatePaging.tsx
  src/hooks/debate/useDetailDebate.tsx
  src/hooks/keywords/usePostSearchWord.tsx
  src/interfaces/worry.ts
  src/pages/board/mbti.tsx
  src/pages/debate/detail.tsx
  src/pages/main/hotBoard.tsx
  src/pages/search/moreBoardResult.tsx
  src/pages/search/moreDebateResult.tsx
  src/pages/search/moreMatchingResult.tsx
  src/pages/search/result.tsx
  src/pages/userPage/UserPage.tsx
  src/pages/userPage/mypage.tsx
Labels: fix
